#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

insmod net
insmod efinet
insmod tftp
net_add_addr efinet1:link efinet1 192.168.188.50
source (tftp,192.168.188.98)/grub_conf
